version: '3'
services:
  django:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
  nginx_container:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/static/:/var/www/static/
    ports:
      - 80:80
